language: cpp
compiler:
  - gcc
  - clang
before_install:
  - sudo add-apt-repository -y ppa:yubico/stable
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y --no-install-recommends libyubikey-dev libykpers-1-dev qt4-qmake libqt4-dev
install:
  - qmake 'CONFIG += debug'
  - make all
script: make check
